title: Carousels
modelClass: Travis\Carousel\Models\Carousel
list: $/travis/carousel/models/carousel/columns.yaml
recordUrl: 'travis/carousel/carousels/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
